### ISSUE TITLE
disk area light with low roughness values break dof bokeh

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-shaders#13]
Values below 0.1 (exactly) or using a very dark roughness texture with dof:

<img width="285" alt="Screenshot 2024-03-01 at 16 59 29" src="https://github.com/pex-gl/pex-shaders/assets/1636460/57a395e5-5b51-4540-a673-1f831594dac2">

Need some double check/commenting of the hardcoded values here:

https://github.com/pex-gl/pex-shaders/blob/8aef7103913dfd73105f1ea23e7c4849fef860bb/shaders/chunks/metallic-roughness.glsl.js#L7-L10

https://github.com/pex-gl/pex-shaders/blob/8aef7103913dfd73105f1ea23e7c4849fef860bb/shaders/chunks/metallic-roughness.glsl.js#L71

https://github.com/pex-gl/pex-shaders/blob/8aef7103913dfd73105f1ea23e7c4849fef860bb/shaders/chunks/metallic-roughness.glsl.js#L75

To see if that matches standard frag:

https://github.com/pex-gl/pex-shaders/blob/8aef7103913dfd73105f1ea23e7c4849fef860bb/shaders/pipeline/standard.frag.js#L197-L198

**Comment by vorg** [comment]
Is that pex-renderer@last-stable, nodes/fx/rg or new DOF code?

**Comment by dmnsgn** [comment]
The issue is actually coming from disk area light producing negative values. Fixed by `max(values, vec3(0.0))`.

Related: https://github.com/selfshadow/ltc_code/issues/9
