### ISSUE TITLE
Use bicubic sampling for transmission

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-shaders#15]
https://web.archive.org/web/20200917060547/https://lusion.co/work/maxmara-bearing-gifts/

Our current implementation looks like this
![transparency_blurry](https://github.com/pex-gl/pex-shaders/assets/171001/86138a28-3e95-4a11-91de-9297a1467d7f)

With bicubic 
![transparency_blurry_bicubic](https://github.com/pex-gl/pex-shaders/assets/171001/ef4f3eac-f89b-406c-b863-1d322b8339ee)

Example implementation here https://github.com/mrdoob/three.js/pull/25483

![218288515-b991be6d-58a4-4db1-9e1a-be4e733dbdac](https://github.com/pex-gl/pex-shaders/assets/171001/a46ca258-c9fb-467d-9e82-ce7b26be2fb2)

**Comment by dmnsgn** [comment]
Before:
![transmission-filter-before](https://github.com/pex-gl/pex-shaders/assets/1636460/01765c47-f18e-4d55-ae7f-14dd1d38db7c)

After:
![transmission-filter-after](https://github.com/pex-gl/pex-shaders/assets/1636460/c4a2a393-a8a4-453e-b6a6-d861188187c9)
