### ISSUE TITLE
Move before lighting hook actually before lighting

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-shaders#17]

**Comment by dmnsgn** [comment]
One unexpected consequence is that it is harder to hack metallic for instance now, eg. this happens too late now:
```js
BEFORE_LIGHTING: /* glsl */ `
data.metallic = step(0.5, vNoiseAmount);
data.baseColor = mix(vec3(2.0, 0.4, 0.0), vec3(1.0), data.metallic);
        `,
```

Should that be another hook? `BEFORE_TEXTURES` is already not very explicit (and not really correct) so what would be the name, AFTER_MATERIAL_MODEL ? 🤨

**Comment by vorg** [comment]
```
data.metallic = step(0.5, vNoiseAmount);
```

too late for what? if you wanna hack metallic to impact color etc? Then we probably need AFTER_MATERIAL_MODEL or AFTER_TEXTURES?

BEFORE_TEXTURES is for hacking uvs
BEFORE_LIGHTING is before lights for PBR overwrites
