### ISSUE TITLE
Clarify alphaRoughness vs linearRoughness vs roughness

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-shaders#6]
Different names are used in different places causing differences in e.g. D_GGX and MicrofacetDistribution which should be merged.

**Comment by dmnsgn** [comment]
We now use `roughness` ([0, 1]) / `linearRoughness` ([roughness^2](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#microfacet-surfaces)) everywhere (corresponding to glTF-Sample-Viewer's perceptualRoughness/alphaRoughness).
